### ISSUE TITLE
项目有几个问题，求解答

### ISSUE THREAD

**Issue by cilla123** [ikcamp/iKtalk#2]
今天尝试去看了下代码，觉得很有意思，但是有以下问题：
1.运行了下web端的，我是mac电脑，电脑的谷歌浏览器，可以正常运行，但是我用手机打开网页的时候，出现黑屏，不能用，相机也调不起
2.打包rn项目到安卓手机上，发现闪退，无法使用

求解答

**Comment by dail** [comment]
相机调用不起来，感觉是权限问题，你检查一下你的浏览器设置。

**Comment by kyoko-df** [comment]
1.先确保你使用的浏览器支持webrtc（iOS不支持），另一点webrtc目前要求服务器强制https（自签证书不一定能通过浏览器认证），非http请求只支持localhost，电脑端可以通过localhost解决，手机端可能需要通过代理方式运行。
2.该项目书中介绍了cordova打包，rn部分当时未能全部完成，rn项目可以看书中的hacknews部分，后期会考虑完善这部分代码。
