### ISSUE TITLE
cordova 无法编译打包通过@android studio 3.0

### ISSUE THREAD

**Issue by alwaysgot200** [ikcamp/iKtalk#3]
买了这本书， 试了一下去编译这个案例， 结果不通

（1）我使用的是android studio 3.0， 之前已经确保react native和 cordova的开发环境是工作的
（2）server and client 是可以运行起来的， 就是 14.1.3中Cordova打包这一节编译不通， 遇到很多错误；
（3）书上说， client 目录中的代码编译完成后， 把client/build目录中的文件全都复制到client/www目录中， 不知所云， 因为根本没有client/build这个目录， 编译不通过呀

**Comment by alwaysgot200** [comment]
client目录中运行  npm build没有任何的反应， NODE_ENV=production 或 developement 都一样

**Comment by alwaysgot200** [comment]
终地在android studio3.0上编译通过了：
（1）添加 flavorDimensions "debug","release"， 必须做；并在productFlavors中加dimension "debug" ， dimension "release"  如下：

defaultConfig {
    applicationId privateHelpers.extractStringFromManifest("package")
    if (cdvMinSdkVersion != null) {
        minSdkVersion cdvMinSdkVersion
    }
    flavorDimensions "debug","release"
}

productFlavors {
    armv7 {
        dimension "debug"
        versionCode defaultConfig.versionCode * 10 + 2
        ndk {
            abiFilters "armeabi-v7a", ""
        }
    }
    x86 {
        dimension "release"
        versionCode defaultConfig.versionCode * 10 + 4
        ndk {
            abiFilters "x86", ""
        }
    }
    all {
        ndk {
            abiFilters "all", ""
        }
    }
}

（2）引用的模块方式变量了
dependencies {
    compile fileTree(include: '*.jar', dir: 'libs')
    // SUB-PROJECT DEPENDENCIES START
    // debugCompile project(path: 'CordovaLib', configuration: 'debug')
    // releaseCompile project(path: 'CordovaLib', configuration: 'release')
    implementation project(':CordovaLib')
    // SUB-PROJECT DEPENDENCIES END
}

（3）此外，第一次加载时，要在 files/ invalide the cache and restart，
然后我使用的gradle是4.1版， 要使用对应正确的gradle插件版本3.0.1
dependencies {
    classpath 'com.android.tools.build:gradle:3.0.1'//这个号必须与android studio的版本号一致
｝

**Comment by kyoko-df** [comment]
build目录的确是通过create react
app生成然后copy到www目录下，gradle的编译环境的确有差异，以后我们会注明gradle的版本，感谢您的回复和解决方案。

2018-03-05 23:21 GMT+08:00 ruixiwu <notifications@github.com>:

**Comment by alwaysgot200** [comment]
kyoko-df：
build目录通过create react app生成然后copy到www目录下？
如何做？项目的client目录不是已经有了吗？ 如何还要运行create react app??
能不能说的更加详细一些？？

**Comment by alwaysgot200** [comment]
弄清楚了：一开始运行npm build没有反应， 然后运行npm run build就好了。
